insert into Courses (id, course_name) values (1, 'Research and Development');
insert into Courses (id, course_name) values (2, 'Engineering');
insert into Courses (id, course_name) values (3, 'Legal');
insert into Courses (id, course_name) values (4, 'Support');
insert into Courses (id, course_name) values (5, 'Marketing');
insert into Courses (id, course_name) values (6, 'Marketing');
insert into Courses (id, course_name) values (7, 'Sales');
insert into Courses (id, course_name) values (8, 'Legal');
insert into Courses (id, course_name) values (9, 'Research and Development');
insert into Courses (id, course_name) values (10, 'Support');
