insert into courses (id, course_name, hour) values (1, 'Research and Development', '5:32 PM');
insert into courses (id, course_name, hour) values (2, 'Engineering', '5:19 AM');
insert into courses (id, course_name, hour) values (3, 'Legal', '2:46 PM');
insert into courses (id, course_name, hour) values (4, 'Support', '2:57 PM');
insert into courses (id, course_name, hour) values (5, 'Marketing', '2:31 AM');
insert into courses (id, course_name, hour) values (6, 'Marketing', '2:06 PM');
insert into courses (id, course_name, hour) values (7, 'Sales', '6:07 AM');
insert into courses (id, course_name, hour) values (8, 'Legal', '4:38 PM');
insert into courses (id, course_name, hour) values (9, 'Research and Development', '7:19 PM');
insert into courses (id, course_name, hour) values (10, 'Support', '4:17 AM');
