insert into students (id, full_name, major) values (1, 'Ruthi', 'Recruiting Manager');
insert into students (id, full_name, major) values (2, 'Reina', 'Research Nurse');
insert into students (id, full_name, major) values (3, 'Amitie', 'Help Desk Technician');
insert into students (id, full_name, major) values (4, 'Charil', 'Design Engineer');
insert into students (id, full_name, major) values (5, 'Esdras', 'Help Desk Operator');
insert into students (id, full_name, major) values (6, 'Inger', 'Project Manager');
insert into students (id, full_name, major) values (7, 'Munroe', 'Staff Scientist');
insert into students (id, full_name, major) values (8, 'Florian', 'Graphic Designer');
insert into students (id, full_name, major) values (9, 'Jami', 'Research Nurse');
insert into students (id, full_name, major) values (10, 'Pier', 'Compensation Analyst');
insert into students (id, full_name, major) values (11, 'Dode', 'Social Worker');
insert into students (id, full_name, major) values (12, 'Cassondra', 'Web Designer III');
insert into students (id, full_name, major) values (13, 'Hubey', 'Marketing Assistant');
insert into students (id, full_name, major) values (14, 'Madelene', 'Assistant Professor');
insert into students (id, full_name, major) values (15, 'Kerr', 'Information Systems Manager');
insert into students (id, full_name, major) values (16, 'Shaughn', 'Computer Systems Analyst IV');
insert into students (id, full_name, major) values (17, 'Kerry', 'VP Product Management');
insert into students (id, full_name, major) values (18, 'Huntley', 'Desktop Support Technician');
insert into students (id, full_name, major) values (19, 'Leticia', 'Nuclear Power Engineer');
insert into students (id, full_name, major) values (20, 'Julian', 'Accountant III');
insert into students (id, full_name, major) values (21, 'Yettie', 'Safety Technician IV');
insert into students (id, full_name, major) values (22, 'Miguelita', 'Food Chemist');
insert into students (id, full_name, major) values (23, 'Dame', 'Geologist IV');
insert into students (id, full_name, major) values (24, 'Meredith', 'Software Consultant');
insert into students (id, full_name, major) values (25, 'Greggory', 'Payment Adjustment Coordinator');
insert into students (id, full_name, major) values (26, 'Emmey', 'Geologist III');
insert into students (id, full_name, major) values (27, 'Quent', 'Marketing Manager');
insert into students (id, full_name, major) values (28, 'Francis', 'Senior Sales Associate');
insert into students (id, full_name, major) values (29, 'Abdel', 'Programmer Analyst IV');
insert into students (id, full_name, major) values (30, 'Dela', 'Internal Auditor');
insert into students (id, full_name, major) values (31, 'Koressa', 'Teacher');
insert into students (id, full_name, major) values (32, 'Clerc', 'Professor');
insert into students (id, full_name, major) values (33, 'Winnifred', 'Librarian');
insert into students (id, full_name, major) values (34, 'Roslyn', 'Marketing Assistant');
insert into students (id, full_name, major) values (35, 'Babara', 'Mechanical Systems Engineer');
insert into students (id, full_name, major) values (36, 'Maris', 'Nuclear Power Engineer');
insert into students (id, full_name, major) values (37, 'Inesita', 'Legal Assistant');
insert into students (id, full_name, major) values (38, 'Torin', 'Programmer I');
insert into students (id, full_name, major) values (39, 'Ashby', 'Actuary');
insert into students (id, full_name, major) values (40, 'Hercule', 'Staff Accountant I');
insert into students (id, full_name, major) values (41, 'Ollie', 'Web Developer I');
insert into students (id, full_name, major) values (42, 'Perice', 'Food Chemist');
insert into students (id, full_name, major) values (43, 'Annaliese', 'Food Chemist');
insert into students (id, full_name, major) values (44, 'Elias', 'Civil Engineer');
insert into students (id, full_name, major) values (45, 'Leonelle', 'Professor');
insert into students (id, full_name, major) values (46, 'Fonsie', 'Statistician II');
insert into students (id, full_name, major) values (47, 'Clair', 'Operator');
insert into students (id, full_name, major) values (48, 'Ebony', 'Quality Control Specialist');
insert into students (id, full_name, major) values (49, 'Marjie', 'Web Designer II');
insert into students (id, full_name, major) values (50, 'Anjanette', 'Structural Analysis Engineer');
insert into students (id, full_name, major) values (51, 'Hugo', 'Assistant Media Planner');
insert into students (id, full_name, major) values (52, 'Stephan', 'Research Assistant I');
insert into students (id, full_name, major) values (53, 'Ranna', 'Marketing Manager');
insert into students (id, full_name, major) values (54, 'Jackie', 'VP Accounting');
insert into students (id, full_name, major) values (55, 'Kati', 'Food Chemist');
insert into students (id, full_name, major) values (56, 'Rudy', 'Quality Engineer');
insert into students (id, full_name, major) values (57, 'Carlynne', 'Research Associate');
insert into students (id, full_name, major) values (58, 'Spenser', 'Senior Developer');
insert into students (id, full_name, major) values (59, 'Thom', 'Chemical Engineer');
insert into students (id, full_name, major) values (60, 'Tamiko', 'Environmental Tech');
insert into students (id, full_name, major) values (61, 'Susannah', 'Product Engineer');
insert into students (id, full_name, major) values (62, 'Tierney', 'Product Engineer');
insert into students (id, full_name, major) values (63, 'Garrick', 'Research Nurse');
insert into students (id, full_name, major) values (64, 'Skye', 'Senior Financial Analyst');
insert into students (id, full_name, major) values (65, 'Bettine', 'Marketing Assistant');
insert into students (id, full_name, major) values (66, 'Ginevra', 'Safety Technician IV');
insert into students (id, full_name, major) values (67, 'Parry', 'Design Engineer');
insert into students (id, full_name, major) values (68, 'Bradan', 'Design Engineer');
insert into students (id, full_name, major) values (69, 'Booth', 'GIS Technical Architect');
insert into students (id, full_name, major) values (70, 'Brodie', 'Internal Auditor');
insert into students (id, full_name, major) values (71, 'Crystal', 'Computer Systems Analyst IV');
insert into students (id, full_name, major) values (72, 'Hortense', 'Senior Sales Associate');
insert into students (id, full_name, major) values (73, 'Berny', 'Associate Professor');
insert into students (id, full_name, major) values (74, 'Oliy', 'Administrative Officer');
insert into students (id, full_name, major) values (75, 'Skippie', 'Environmental Tech');
insert into students (id, full_name, major) values (76, 'Archie', 'Administrative Assistant IV');
insert into students (id, full_name, major) values (77, 'Vannie', 'Computer Systems Analyst III');
insert into students (id, full_name, major) values (78, 'Auberon', 'Senior Editor');
insert into students (id, full_name, major) values (79, 'Vita', 'Developer IV');
insert into students (id, full_name, major) values (80, 'Rochelle', 'Speech Pathologist');
insert into students (id, full_name, major) values (81, 'Prisca', 'Administrative Officer');
insert into students (id, full_name, major) values (82, 'Chelsy', 'Financial Advisor');
insert into students (id, full_name, major) values (83, 'Idaline', 'Librarian');
insert into students (id, full_name, major) values (84, 'Gratia', 'Tax Accountant');
insert into students (id, full_name, major) values (85, 'Torin', 'Data Coordinator');
insert into students (id, full_name, major) values (86, 'Myles', 'Programmer Analyst III');
insert into students (id, full_name, major) values (87, 'Ross', 'Technical Writer');
insert into students (id, full_name, major) values (88, 'Jaimie', 'Computer Systems Analyst IV');
insert into students (id, full_name, major) values (89, 'Benoite', 'Nurse');
insert into students (id, full_name, major) values (90, 'Pollyanna', 'Database Administrator IV');
insert into students (id, full_name, major) values (91, 'Tallulah', 'Budget/Accounting Analyst I');
insert into students (id, full_name, major) values (92, 'Aguistin', 'Marketing Manager');
insert into students (id, full_name, major) values (93, 'Catlin', 'Senior Sales Associate');
insert into students (id, full_name, major) values (94, 'Shadow', 'Research Associate');
insert into students (id, full_name, major) values (95, 'Ilyse', 'Assistant Manager');
insert into students (id, full_name, major) values (96, 'Tannie', 'Web Developer II');
insert into students (id, full_name, major) values (97, 'Gallard', 'Account Representative III');
insert into students (id, full_name, major) values (98, 'Jamey', 'Dental Hygienist');
insert into students (id, full_name, major) values (99, 'Barbette', 'Office Assistant I');
insert into students (id, full_name, major) values (100, 'Abbey', 'Dental Hygienist');
insert into students (id, full_name, major) values (101, 'Shaun', 'Dental Hygienist');
insert into students (id, full_name, major) values (102, 'Gretna', 'Structural Engineer');
insert into students (id, full_name, major) values (103, 'Kordula', 'Design Engineer');
insert into students (id, full_name, major) values (104, 'Malvina', 'Environmental Tech');
insert into students (id, full_name, major) values (105, 'Gil', 'Accounting Assistant I');
insert into students (id, full_name, major) values (106, 'Renato', 'Senior Editor');
insert into students (id, full_name, major) values (107, 'Merissa', 'Financial Advisor');
insert into students (id, full_name, major) values (108, 'Ciro', 'Quality Control Specialist');
insert into students (id, full_name, major) values (109, 'Margarette', 'Paralegal');
insert into students (id, full_name, major) values (110, 'Shayla', 'Payment Adjustment Coordinator');
insert into students (id, full_name, major) values (111, 'Robyn', 'Senior Quality Engineer');
insert into students (id, full_name, major) values (112, 'Lacy', 'Physical Therapy Assistant');
insert into students (id, full_name, major) values (113, 'Ronald', 'Marketing Manager');
insert into students (id, full_name, major) values (114, 'Man', 'Accountant III');
insert into students (id, full_name, major) values (115, 'Joana', 'Mechanical Systems Engineer');
insert into students (id, full_name, major) values (116, 'Arlan', 'VP Product Management');
insert into students (id, full_name, major) values (117, 'Cher', 'Speech Pathologist');
insert into students (id, full_name, major) values (118, 'Storm', 'Clinical Specialist');
insert into students (id, full_name, major) values (119, 'Kristine', 'Editor');
insert into students (id, full_name, major) values (120, 'Florrie', 'Junior Executive');
insert into students (id, full_name, major) values (121, 'Dyane', 'Senior Quality Engineer');
insert into students (id, full_name, major) values (122, 'Shamus', 'Structural Engineer');
insert into students (id, full_name, major) values (123, 'Antonin', 'Accountant IV');
insert into students (id, full_name, major) values (124, 'Turner', 'Budget/Accounting Analyst III');
insert into students (id, full_name, major) values (125, 'Edmund', 'Junior Executive');
insert into students (id, full_name, major) values (126, 'Althea', 'Senior Quality Engineer');
insert into students (id, full_name, major) values (127, 'Phylys', 'Nuclear Power Engineer');
insert into students (id, full_name, major) values (128, 'Veda', 'Account Coordinator');
insert into students (id, full_name, major) values (129, 'Guillema', 'Clinical Specialist');
insert into students (id, full_name, major) values (130, 'Tedra', 'Civil Engineer');
insert into students (id, full_name, major) values (131, 'Theo', 'Structural Analysis Engineer');
insert into students (id, full_name, major) values (132, 'Antone', 'Assistant Professor');
insert into students (id, full_name, major) values (133, 'Agnes', 'Speech Pathologist');
insert into students (id, full_name, major) values (134, 'Baron', 'Executive Secretary');
insert into students (id, full_name, major) values (135, 'Barnie', 'Human Resources Assistant I');
insert into students (id, full_name, major) values (136, 'Davida', 'Product Engineer');
insert into students (id, full_name, major) values (137, 'Cecilius', 'Budget/Accounting Analyst I');
insert into students (id, full_name, major) values (138, 'Merilee', 'Sales Representative');
insert into students (id, full_name, major) values (139, 'Helaine', 'Accounting Assistant III');
insert into students (id, full_name, major) values (140, 'Hestia', 'Compensation Analyst');
insert into students (id, full_name, major) values (141, 'Judith', 'Nuclear Power Engineer');
insert into students (id, full_name, major) values (142, 'Midge', 'Marketing Assistant');
insert into students (id, full_name, major) values (143, 'Korrie', 'Chief Design Engineer');
insert into students (id, full_name, major) values (144, 'Giulia', 'Mechanical Systems Engineer');
insert into students (id, full_name, major) values (145, 'Piper', 'Software Engineer I');
insert into students (id, full_name, major) values (146, 'Aldin', 'Assistant Manager');
insert into students (id, full_name, major) values (147, 'Babbette', 'Technical Writer');
insert into students (id, full_name, major) values (148, 'Hendrick', 'Director of Sales');
insert into students (id, full_name, major) values (149, 'Teodora', 'Physical Therapy Assistant');
insert into students (id, full_name, major) values (150, 'Herrick', 'Human Resources Assistant I');
insert into students (id, full_name, major) values (151, 'Kathryne', 'Librarian');
insert into students (id, full_name, major) values (152, 'Dianemarie', 'Geologist II');
insert into students (id, full_name, major) values (153, 'Alic', 'Senior Sales Associate');
insert into students (id, full_name, major) values (154, 'Cherry', 'Geological Engineer');
insert into students (id, full_name, major) values (155, 'Heather', 'Analyst Programmer');
insert into students (id, full_name, major) values (156, 'Henrietta', 'Help Desk Technician');
insert into students (id, full_name, major) values (157, 'Sigfried', 'Graphic Designer');
insert into students (id, full_name, major) values (158, 'My', 'Help Desk Technician');
insert into students (id, full_name, major) values (159, 'Gallagher', 'Director of Sales');
insert into students (id, full_name, major) values (160, 'Clemence', 'Computer Systems Analyst I');
insert into students (id, full_name, major) values (161, 'Kettie', 'Environmental Specialist');
insert into students (id, full_name, major) values (162, 'Zach', 'Budget/Accounting Analyst I');
insert into students (id, full_name, major) values (163, 'Laureen', 'Social Worker');
insert into students (id, full_name, major) values (164, 'Verine', 'Nurse');
insert into students (id, full_name, major) values (165, 'Nathan', 'Editor');
insert into students (id, full_name, major) values (166, 'Pennie', 'Product Engineer');
insert into students (id, full_name, major) values (167, 'Abe', 'Environmental Tech');
insert into students (id, full_name, major) values (168, 'Evie', 'Senior Quality Engineer');
insert into students (id, full_name, major) values (169, 'Emlynne', 'Recruiting Manager');
insert into students (id, full_name, major) values (170, 'Larisa', 'Financial Advisor');
insert into students (id, full_name, major) values (171, 'Berkie', 'Developer I');
insert into students (id, full_name, major) values (172, 'Gonzalo', 'Design Engineer');
insert into students (id, full_name, major) values (173, 'Ave', 'Senior Financial Analyst');
insert into students (id, full_name, major) values (174, 'Lynsey', 'Nurse Practicioner');
insert into students (id, full_name, major) values (175, 'Patin', 'Assistant Professor');
insert into students (id, full_name, major) values (176, 'Nerty', 'Account Representative I');
insert into students (id, full_name, major) values (177, 'Lurette', 'Help Desk Operator');
insert into students (id, full_name, major) values (178, 'Christean', 'Computer Systems Analyst II');
insert into students (id, full_name, major) values (179, 'Auberon', 'Budget/Accounting Analyst II');
insert into students (id, full_name, major) values (180, 'Johny', 'Senior Editor');
insert into students (id, full_name, major) values (181, 'Richart', 'Technical Writer');
insert into students (id, full_name, major) values (182, 'Mal', 'Actuary');
insert into students (id, full_name, major) values (183, 'Luci', 'Statistician II');
insert into students (id, full_name, major) values (184, 'Lockwood', 'Internal Auditor');
insert into students (id, full_name, major) values (185, 'Martguerita', 'Analyst Programmer');
insert into students (id, full_name, major) values (186, 'Alie', 'Assistant Media Planner');
insert into students (id, full_name, major) values (187, 'Humberto', 'Safety Technician I');
insert into students (id, full_name, major) values (188, 'Min', 'Sales Associate');
insert into students (id, full_name, major) values (189, 'Cornelia', 'Nurse Practicioner');
insert into students (id, full_name, major) values (190, 'Harris', 'Human Resources Assistant I');
insert into students (id, full_name, major) values (191, 'Gabrila', 'Account Representative II');
insert into students (id, full_name, major) values (192, 'Brana', 'Registered Nurse');
insert into students (id, full_name, major) values (193, 'Sidnee', 'Account Representative II');
insert into students (id, full_name, major) values (194, 'Correy', 'Civil Engineer');
insert into students (id, full_name, major) values (195, 'Minni', 'Design Engineer');
insert into students (id, full_name, major) values (196, 'Clemens', 'Information Systems Manager');
insert into students (id, full_name, major) values (197, 'Marjory', 'VP Product Management');
insert into students (id, full_name, major) values (198, 'Charlton', 'Assistant Media Planner');
insert into students (id, full_name, major) values (199, 'Gweneth', 'Chief Design Engineer');
insert into students (id, full_name, major) values (200, 'Meyer', 'Clinical Specialist');
insert into students (id, full_name, major) values (201, 'Beaufort', 'Account Executive');
insert into students (id, full_name, major) values (202, 'Cointon', 'Data Coordinator');
insert into students (id, full_name, major) values (203, 'Catina', 'Junior Executive');
insert into students (id, full_name, major) values (204, 'Horst', 'Nurse Practicioner');
insert into students (id, full_name, major) values (205, 'Kynthia', 'Human Resources Assistant II');
insert into students (id, full_name, major) values (206, 'Beale', 'Assistant Media Planner');
insert into students (id, full_name, major) values (207, 'Carey', 'General Manager');
insert into students (id, full_name, major) values (208, 'Jodi', 'Nurse Practicioner');
insert into students (id, full_name, major) values (209, 'Monty', 'Financial Advisor');
insert into students (id, full_name, major) values (210, 'Ashien', 'Web Designer I');
insert into students (id, full_name, major) values (211, 'Trudey', 'Librarian');
insert into students (id, full_name, major) values (212, 'Shelba', 'Software Consultant');
insert into students (id, full_name, major) values (213, 'Sergeant', 'Social Worker');
insert into students (id, full_name, major) values (214, 'Allan', 'Food Chemist');
insert into students (id, full_name, major) values (215, 'Stavros', 'Analyst Programmer');
insert into students (id, full_name, major) values (216, 'Stephani', 'Technical Writer');
insert into students (id, full_name, major) values (217, 'Dacie', 'Software Engineer I');
insert into students (id, full_name, major) values (218, 'Iris', 'Community Outreach Specialist');
insert into students (id, full_name, major) values (219, 'Dominick', 'Product Engineer');
insert into students (id, full_name, major) values (220, 'Gilberto', 'Administrative Officer');
insert into students (id, full_name, major) values (221, 'Goddart', 'Staff Scientist');
insert into students (id, full_name, major) values (222, 'Dev', 'Senior Cost Accountant');
insert into students (id, full_name, major) values (223, 'Mommy', 'Quality Engineer');
insert into students (id, full_name, major) values (224, 'Reube', 'Information Systems Manager');
insert into students (id, full_name, major) values (225, 'Ranique', 'Health Coach I');
insert into students (id, full_name, major) values (226, 'Yolande', 'Food Chemist');
insert into students (id, full_name, major) values (227, 'Melvin', 'Compensation Analyst');
insert into students (id, full_name, major) values (228, 'Ninnette', 'Accounting Assistant I');
insert into students (id, full_name, major) values (229, 'Simonette', 'Staff Accountant II');
insert into students (id, full_name, major) values (230, 'Piggy', 'VP Sales');
insert into students (id, full_name, major) values (231, 'Mart', 'Financial Advisor');
insert into students (id, full_name, major) values (232, 'Burch', 'Business Systems Development Analyst');
insert into students (id, full_name, major) values (233, 'Dallas', 'Programmer Analyst II');
insert into students (id, full_name, major) values (234, 'Gay', 'Cost Accountant');
insert into students (id, full_name, major) values (235, 'Rafa', 'Assistant Media Planner');
insert into students (id, full_name, major) values (236, 'Darcie', 'VP Sales');
insert into students (id, full_name, major) values (237, 'Esther', 'Human Resources Assistant I');
insert into students (id, full_name, major) values (238, 'Amaleta', 'Payment Adjustment Coordinator');
insert into students (id, full_name, major) values (239, 'Sallyanne', 'Speech Pathologist');
insert into students (id, full_name, major) values (240, 'Yettie', 'Structural Engineer');
insert into students (id, full_name, major) values (241, 'Wynn', 'VP Quality Control');
insert into students (id, full_name, major) values (242, 'Giffard', 'Legal Assistant');
insert into students (id, full_name, major) values (243, 'Cecilla', 'VP Accounting');
insert into students (id, full_name, major) values (244, 'Geoffry', 'Recruiting Manager');
insert into students (id, full_name, major) values (245, 'Sayre', 'Clinical Specialist');
insert into students (id, full_name, major) values (246, 'Blake', 'Project Manager');
insert into students (id, full_name, major) values (247, 'Carolyn', 'Office Assistant II');
insert into students (id, full_name, major) values (248, 'Salvador', 'Health Coach IV');
insert into students (id, full_name, major) values (249, 'Eloise', 'Structural Analysis Engineer');
insert into students (id, full_name, major) values (250, 'Verney', 'Assistant Professor');
insert into students (id, full_name, major) values (251, 'Janis', 'Research Nurse');
insert into students (id, full_name, major) values (252, 'Vere', 'Office Assistant I');
insert into students (id, full_name, major) values (253, 'Ram', 'Teacher');
insert into students (id, full_name, major) values (254, 'Maryrose', 'Senior Developer');
insert into students (id, full_name, major) values (255, 'Billi', 'Administrative Officer');
insert into students (id, full_name, major) values (256, 'Iggie', 'Developer I');
insert into students (id, full_name, major) values (257, 'Gertie', 'Environmental Specialist');
insert into students (id, full_name, major) values (258, 'Simone', 'VP Product Management');
insert into students (id, full_name, major) values (259, 'Sergeant', 'Senior Developer');
insert into students (id, full_name, major) values (260, 'Llywellyn', 'Project Manager');
insert into students (id, full_name, major) values (261, 'Jammie', 'Payment Adjustment Coordinator');
insert into students (id, full_name, major) values (262, 'Michaeline', 'Sales Representative');
insert into students (id, full_name, major) values (263, 'Pauly', 'Recruiting Manager');
insert into students (id, full_name, major) values (264, 'Tate', 'Environmental Tech');
insert into students (id, full_name, major) values (265, 'Jaquelyn', 'GIS Technical Architect');
insert into students (id, full_name, major) values (266, 'Dorrie', 'Geologist I');
insert into students (id, full_name, major) values (267, 'Diahann', 'Staff Scientist');
insert into students (id, full_name, major) values (268, 'Stepha', 'Quality Control Specialist');
insert into students (id, full_name, major) values (269, 'Araldo', 'Staff Scientist');
insert into students (id, full_name, major) values (270, 'Maurizia', 'Programmer I');
insert into students (id, full_name, major) values (271, 'Klarrisa', 'VP Product Management');
insert into students (id, full_name, major) values (272, 'Rana', 'VP Product Management');
insert into students (id, full_name, major) values (273, 'Lorianne', 'Quality Engineer');
insert into students (id, full_name, major) values (274, 'Antoinette', 'Associate Professor');
insert into students (id, full_name, major) values (275, 'Irwin', 'Teacher');
insert into students (id, full_name, major) values (276, 'Svend', 'Registered Nurse');
insert into students (id, full_name, major) values (277, 'Dale', 'Internal Auditor');
insert into students (id, full_name, major) values (278, 'Elnore', 'Staff Accountant III');
insert into students (id, full_name, major) values (279, 'Steffen', 'Engineer I');
insert into students (id, full_name, major) values (280, 'Vevay', 'Software Consultant');
insert into students (id, full_name, major) values (281, 'Anson', 'Web Designer IV');
insert into students (id, full_name, major) values (282, 'Aeriela', 'General Manager');
insert into students (id, full_name, major) values (283, 'Toddy', 'Chief Design Engineer');
insert into students (id, full_name, major) values (284, 'Gilberto', 'Analyst Programmer');
insert into students (id, full_name, major) values (285, 'Buck', 'Recruiter');
insert into students (id, full_name, major) values (286, 'Haleigh', 'VP Product Management');
insert into students (id, full_name, major) values (287, 'Katee', 'GIS Technical Architect');
insert into students (id, full_name, major) values (288, 'Hynda', 'Recruiting Manager');
insert into students (id, full_name, major) values (289, 'Salomi', 'Financial Advisor');
insert into students (id, full_name, major) values (290, 'Leonidas', 'Accountant III');
insert into students (id, full_name, major) values (291, 'Margarethe', 'Pharmacist');
insert into students (id, full_name, major) values (292, 'Amity', 'Editor');
insert into students (id, full_name, major) values (293, 'Vance', 'Teacher');
insert into students (id, full_name, major) values (294, 'Pearce', 'VP Marketing');
insert into students (id, full_name, major) values (295, 'Elnar', 'Computer Systems Analyst I');
insert into students (id, full_name, major) values (296, 'Thea', 'Mechanical Systems Engineer');
insert into students (id, full_name, major) values (297, 'Valeda', 'Administrative Assistant II');
insert into students (id, full_name, major) values (298, 'Dorie', 'Desktop Support Technician');
insert into students (id, full_name, major) values (299, 'Caldwell', 'VP Marketing');
insert into students (id, full_name, major) values (300, 'Jenni', 'General Manager');
insert into students (id, full_name, major) values (301, 'Isabelle', 'VP Product Management');
insert into students (id, full_name, major) values (302, 'Grady', 'Professor');
insert into students (id, full_name, major) values (303, 'Devi', 'Civil Engineer');
insert into students (id, full_name, major) values (304, 'Becki', 'Information Systems Manager');
insert into students (id, full_name, major) values (305, 'Forbes', 'Structural Engineer');
insert into students (id, full_name, major) values (306, 'Hastings', 'Office Assistant IV');
insert into students (id, full_name, major) values (307, 'Sloan', 'Administrative Assistant III');
insert into students (id, full_name, major) values (308, 'Valma', 'Product Engineer');
insert into students (id, full_name, major) values (309, 'Erich', 'Assistant Manager');
insert into students (id, full_name, major) values (310, 'Edd', 'Staff Accountant I');
insert into students (id, full_name, major) values (311, 'Dorette', 'Junior Executive');
insert into students (id, full_name, major) values (312, 'Agosto', 'Financial Advisor');
insert into students (id, full_name, major) values (313, 'Ruthanne', 'Desktop Support Technician');
insert into students (id, full_name, major) values (314, 'Jory', 'Associate Professor');
insert into students (id, full_name, major) values (315, 'Charyl', 'Director of Sales');
insert into students (id, full_name, major) values (316, 'Philippine', 'Associate Professor');
insert into students (id, full_name, major) values (317, 'Debbie', 'Human Resources Assistant I');
insert into students (id, full_name, major) values (318, 'Sharron', 'Nurse');
insert into students (id, full_name, major) values (319, 'Felix', 'Web Designer I');
insert into students (id, full_name, major) values (320, 'Maura', 'Programmer Analyst III');
insert into students (id, full_name, major) values (321, 'Lesley', 'Quality Engineer');
insert into students (id, full_name, major) values (322, 'Odell', 'Financial Analyst');
insert into students (id, full_name, major) values (323, 'Irvin', 'Civil Engineer');
insert into students (id, full_name, major) values (324, 'Asher', 'Programmer IV');
insert into students (id, full_name, major) values (325, 'Pren', 'Marketing Assistant');
insert into students (id, full_name, major) values (326, 'Keane', 'Structural Engineer');
insert into students (id, full_name, major) values (327, 'Jeralee', 'Environmental Tech');
insert into students (id, full_name, major) values (328, 'Retha', 'Database Administrator IV');
insert into students (id, full_name, major) values (329, 'Jecho', 'Budget/Accounting Analyst IV');
insert into students (id, full_name, major) values (330, 'Annabella', 'Nuclear Power Engineer');
insert into students (id, full_name, major) values (331, 'Ritchie', 'Assistant Media Planner');
insert into students (id, full_name, major) values (332, 'Natassia', 'Account Representative IV');
insert into students (id, full_name, major) values (333, 'Sharity', 'Food Chemist');
insert into students (id, full_name, major) values (334, 'Dougie', 'Help Desk Technician');
insert into students (id, full_name, major) values (335, 'Rickie', 'Food Chemist');
insert into students (id, full_name, major) values (336, 'Arlen', 'Accounting Assistant III');
insert into students (id, full_name, major) values (337, 'Roscoe', 'Assistant Professor');
insert into students (id, full_name, major) values (338, 'Regine', 'Safety Technician I');
insert into students (id, full_name, major) values (339, 'Roch', 'Analyst Programmer');
insert into students (id, full_name, major) values (340, 'Ellis', 'Software Consultant');
insert into students (id, full_name, major) values (341, 'Claudelle', 'Analog Circuit Design manager');
insert into students (id, full_name, major) values (342, 'Cayla', 'VP Marketing');
insert into students (id, full_name, major) values (343, 'Leland', 'Product Engineer');
insert into students (id, full_name, major) values (344, 'Frasquito', 'Technical Writer');
insert into students (id, full_name, major) values (345, 'Francisca', 'Tax Accountant');
insert into students (id, full_name, major) values (346, 'Arlette', 'Systems Administrator IV');
insert into students (id, full_name, major) values (347, 'Josh', 'Junior Executive');
insert into students (id, full_name, major) values (348, 'Clarita', 'Web Designer IV');
insert into students (id, full_name, major) values (349, 'Carita', 'Engineer II');
insert into students (id, full_name, major) values (350, 'Tani', 'Administrative Officer');
insert into students (id, full_name, major) values (351, 'Roseline', 'Nurse');
insert into students (id, full_name, major) values (352, 'Penelope', 'Editor');
insert into students (id, full_name, major) values (353, 'Ora', 'Software Engineer I');
insert into students (id, full_name, major) values (354, 'Son', 'Physical Therapy Assistant');
insert into students (id, full_name, major) values (355, 'Tito', 'Quality Control Specialist');
insert into students (id, full_name, major) values (356, 'Chevalier', 'Associate Professor');
insert into students (id, full_name, major) values (357, 'Dodie', 'Paralegal');
insert into students (id, full_name, major) values (358, 'Kristofer', 'Actuary');
insert into students (id, full_name, major) values (359, 'Lulu', 'Teacher');
insert into students (id, full_name, major) values (360, 'Lezlie', 'Statistician III');
insert into students (id, full_name, major) values (361, 'Aidan', 'Sales Associate');
insert into students (id, full_name, major) values (362, 'Myrta', 'Actuary');
insert into students (id, full_name, major) values (363, 'Kelby', 'Graphic Designer');
insert into students (id, full_name, major) values (364, 'Myrah', 'Staff Scientist');
insert into students (id, full_name, major) values (365, 'Lolly', 'Statistician IV');
insert into students (id, full_name, major) values (366, 'Jessi', 'VP Accounting');
insert into students (id, full_name, major) values (367, 'Meara', 'Speech Pathologist');
insert into students (id, full_name, major) values (368, 'Yvor', 'Operator');
insert into students (id, full_name, major) values (369, 'Herta', 'Recruiting Manager');
insert into students (id, full_name, major) values (370, 'Kelcy', 'Director of Sales');
insert into students (id, full_name, major) values (371, 'Lemar', 'Senior Quality Engineer');
insert into students (id, full_name, major) values (372, 'Dewey', 'Geological Engineer');
insert into students (id, full_name, major) values (373, 'Clemente', 'Editor');
insert into students (id, full_name, major) values (374, 'Darius', 'VP Quality Control');
insert into students (id, full_name, major) values (375, 'Emilio', 'Account Representative II');
insert into students (id, full_name, major) values (376, 'Abbye', 'Environmental Tech');
insert into students (id, full_name, major) values (377, 'Damiano', 'Recruiter');
insert into students (id, full_name, major) values (378, 'Billie', 'Human Resources Manager');
insert into students (id, full_name, major) values (379, 'Sarge', 'Assistant Manager');
insert into students (id, full_name, major) values (380, 'Ange', 'Chief Design Engineer');
insert into students (id, full_name, major) values (381, 'Nomi', 'Account Executive');
insert into students (id, full_name, major) values (382, 'Shaughn', 'Statistician III');
insert into students (id, full_name, major) values (383, 'Kristopher', 'Automation Specialist III');
insert into students (id, full_name, major) values (384, 'Magnum', 'Marketing Assistant');
insert into students (id, full_name, major) values (385, 'Prue', 'Accountant III');
insert into students (id, full_name, major) values (386, 'Nanni', 'Software Engineer I');
insert into students (id, full_name, major) values (387, 'Shandee', 'Associate Professor');
insert into students (id, full_name, major) values (388, 'Veriee', 'Research Associate');
insert into students (id, full_name, major) values (389, 'Hannie', 'Senior Cost Accountant');
insert into students (id, full_name, major) values (390, 'Karil', 'Senior Quality Engineer');
insert into students (id, full_name, major) values (391, 'Leandra', 'Paralegal');
insert into students (id, full_name, major) values (392, 'Sabine', 'Social Worker');
insert into students (id, full_name, major) values (393, 'Cathryn', 'Staff Scientist');
insert into students (id, full_name, major) values (394, 'Igor', 'Software Test Engineer II');
insert into students (id, full_name, major) values (395, 'Hercules', 'Compensation Analyst');
insert into students (id, full_name, major) values (396, 'Lorry', 'Staff Scientist');
insert into students (id, full_name, major) values (397, 'Fax', 'Developer III');
insert into students (id, full_name, major) values (398, 'Claudie', 'Accountant II');
insert into students (id, full_name, major) values (399, 'Steven', 'GIS Technical Architect');
insert into students (id, full_name, major) values (400, 'Frank', 'Human Resources Manager');
insert into students (id, full_name, major) values (401, 'Alexine', 'Sales Associate');
insert into students (id, full_name, major) values (402, 'Kikelia', 'Sales Representative');
insert into students (id, full_name, major) values (403, 'Joelly', 'Mechanical Systems Engineer');
insert into students (id, full_name, major) values (404, 'Gerome', 'Structural Engineer');
insert into students (id, full_name, major) values (405, 'Birgitta', 'Safety Technician IV');
insert into students (id, full_name, major) values (406, 'Bentlee', 'Business Systems Development Analyst');
insert into students (id, full_name, major) values (407, 'Jase', 'Community Outreach Specialist');
insert into students (id, full_name, major) values (408, 'Marline', 'Tax Accountant');
insert into students (id, full_name, major) values (409, 'Kippie', 'Electrical Engineer');
insert into students (id, full_name, major) values (410, 'Sanderson', 'Quality Engineer');
insert into students (id, full_name, major) values (411, 'Clemens', 'Account Representative III');
insert into students (id, full_name, major) values (412, 'Perrine', 'Accountant IV');
insert into students (id, full_name, major) values (413, 'Hope', 'Analyst Programmer');
insert into students (id, full_name, major) values (414, 'Ivan', 'Occupational Therapist');
insert into students (id, full_name, major) values (415, 'Hamish', 'Sales Representative');
insert into students (id, full_name, major) values (416, 'Rich', 'Help Desk Operator');
insert into students (id, full_name, major) values (417, 'Piggy', 'VP Product Management');
insert into students (id, full_name, major) values (418, 'Adda', 'Developer IV');
insert into students (id, full_name, major) values (419, 'Boyd', 'Associate Professor');
insert into students (id, full_name, major) values (420, 'Glori', 'Programmer III');
insert into students (id, full_name, major) values (421, 'Isaiah', 'Account Representative III');
insert into students (id, full_name, major) values (422, 'Farand', 'Executive Secretary');
insert into students (id, full_name, major) values (423, 'Glyn', 'General Manager');
insert into students (id, full_name, major) values (424, 'Thorsten', 'Marketing Manager');
insert into students (id, full_name, major) values (425, 'Esma', 'VP Sales');
insert into students (id, full_name, major) values (426, 'Fritz', 'Desktop Support Technician');
insert into students (id, full_name, major) values (427, 'Keelia', 'Human Resources Manager');
insert into students (id, full_name, major) values (428, 'Raff', 'Automation Specialist IV');
insert into students (id, full_name, major) values (429, 'Helenka', 'Director of Sales');
insert into students (id, full_name, major) values (430, 'Sinclare', 'Assistant Media Planner');
insert into students (id, full_name, major) values (431, 'Barty', 'Director of Sales');
insert into students (id, full_name, major) values (432, 'Celina', 'Marketing Assistant');
insert into students (id, full_name, major) values (433, 'Lyn', 'Tax Accountant');
insert into students (id, full_name, major) values (434, 'Lexi', 'Computer Systems Analyst II');
insert into students (id, full_name, major) values (435, 'Rita', 'Research Nurse');
insert into students (id, full_name, major) values (436, 'Tull', 'Professor');
insert into students (id, full_name, major) values (437, 'Thibaud', 'Speech Pathologist');
insert into students (id, full_name, major) values (438, 'Clyve', 'Food Chemist');
insert into students (id, full_name, major) values (439, 'Trent', 'Marketing Assistant');
insert into students (id, full_name, major) values (440, 'Anastassia', 'Media Manager II');
insert into students (id, full_name, major) values (441, 'Libbie', 'Product Engineer');
insert into students (id, full_name, major) values (442, 'Joannes', 'Health Coach IV');
insert into students (id, full_name, major) values (443, 'Lesley', 'Chief Design Engineer');
insert into students (id, full_name, major) values (444, 'Prudi', 'Project Manager');
insert into students (id, full_name, major) values (445, 'Em', 'Senior Cost Accountant');
insert into students (id, full_name, major) values (446, 'Arley', 'Paralegal');
insert into students (id, full_name, major) values (447, 'Calypso', 'Engineer III');
insert into students (id, full_name, major) values (448, 'Reuben', 'Human Resources Manager');
insert into students (id, full_name, major) values (449, 'Moria', 'Registered Nurse');
insert into students (id, full_name, major) values (450, 'Aksel', 'Programmer Analyst I');
insert into students (id, full_name, major) values (451, 'Sidonia', 'Occupational Therapist');
insert into students (id, full_name, major) values (452, 'Janina', 'Research Assistant I');
insert into students (id, full_name, major) values (453, 'Doti', 'Programmer IV');
insert into students (id, full_name, major) values (454, 'Vita', 'Environmental Specialist');
insert into students (id, full_name, major) values (455, 'Leonhard', 'Nurse');
insert into students (id, full_name, major) values (456, 'Shaylynn', 'Compensation Analyst');
insert into students (id, full_name, major) values (457, 'Carmita', 'Analyst Programmer');
insert into students (id, full_name, major) values (458, 'Levin', 'Geologist I');
insert into students (id, full_name, major) values (459, 'Huntington', 'Senior Developer');
insert into students (id, full_name, major) values (460, 'Adrianna', 'Dental Hygienist');
insert into students (id, full_name, major) values (461, 'Walden', 'Chief Design Engineer');
insert into students (id, full_name, major) values (462, 'Barbabra', 'Assistant Manager');
insert into students (id, full_name, major) values (463, 'Hanson', 'Sales Associate');
insert into students (id, full_name, major) values (464, 'Anya', 'Senior Quality Engineer');
insert into students (id, full_name, major) values (465, 'Delora', 'Director of Sales');
insert into students (id, full_name, major) values (466, 'Tait', 'Systems Administrator I');
insert into students (id, full_name, major) values (467, 'Pammy', 'Occupational Therapist');
insert into students (id, full_name, major) values (468, 'Savina', 'Technical Writer');
insert into students (id, full_name, major) values (469, 'Lorelle', 'Associate Professor');
insert into students (id, full_name, major) values (470, 'Allen', 'Budget/Accounting Analyst II');
insert into students (id, full_name, major) values (471, 'James', 'Dental Hygienist');
insert into students (id, full_name, major) values (472, 'Des', 'Paralegal');
insert into students (id, full_name, major) values (473, 'Raleigh', 'Biostatistician III');
insert into students (id, full_name, major) values (474, 'Elsinore', 'Physical Therapy Assistant');
insert into students (id, full_name, major) values (475, 'Alix', 'Sales Representative');
insert into students (id, full_name, major) values (476, 'Colver', 'Internal Auditor');
insert into students (id, full_name, major) values (477, 'Kelsey', 'Senior Financial Analyst');
insert into students (id, full_name, major) values (478, 'Lyell', 'Chemical Engineer');
insert into students (id, full_name, major) values (479, 'Nikki', 'Help Desk Technician');
insert into students (id, full_name, major) values (480, 'Oriana', 'Editor');
insert into students (id, full_name, major) values (481, 'Orlando', 'Geologist IV');
insert into students (id, full_name, major) values (482, 'Arnuad', 'Recruiter');
insert into students (id, full_name, major) values (483, 'Dulciana', 'VP Product Management');
insert into students (id, full_name, major) values (484, 'Josephina', 'Safety Technician IV');
insert into students (id, full_name, major) values (485, 'Lucienne', 'Junior Executive');
insert into students (id, full_name, major) values (486, 'Meryl', 'Budget/Accounting Analyst I');
insert into students (id, full_name, major) values (487, 'Lek', 'Information Systems Manager');
insert into students (id, full_name, major) values (488, 'Arabele', 'Executive Secretary');
insert into students (id, full_name, major) values (489, 'Tasha', 'Junior Executive');
insert into students (id, full_name, major) values (490, 'Eloisa', 'Accountant IV');
insert into students (id, full_name, major) values (491, 'Barris', 'Budget/Accounting Analyst IV');
insert into students (id, full_name, major) values (492, 'Ally', 'Assistant Media Planner');
insert into students (id, full_name, major) values (493, 'Donnell', 'Desktop Support Technician');
insert into students (id, full_name, major) values (494, 'Annamaria', 'Community Outreach Specialist');
insert into students (id, full_name, major) values (495, 'Miriam', 'Research Nurse');
insert into students (id, full_name, major) values (496, 'Orelee', 'Clinical Specialist');
insert into students (id, full_name, major) values (497, 'Abelard', 'Food Chemist');
insert into students (id, full_name, major) values (498, 'Uriel', 'GIS Technical Architect');
insert into students (id, full_name, major) values (499, 'Marge', 'Actuary');
insert into students (id, full_name, major) values (500, 'Vere', 'Senior Sales Associate');
